"""v3_transcripts

Revision ID: 0df1434883f2
Revises: fdd74cee7615
Create Date: 2026-09-19 07:43:08.646565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df1434883f2'
down_revision: Union[str, None] = 'fdd74cee7615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('ai', 'user', name='transcript_speaker'), nullable=False),
    sa.Column('input_mode', sa.Enum('text', 'voice', name='transcript_input_mode'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('audio_ref', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_interview_id'), 'transcripts', ['interview_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_interview_id'), table_name='transcripts')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
