"""v4_deletion_requests

Revision ID: 8a55fda78a42
Revises: 0df1434883f2
Create Date: 2026-09-19 07:55:35.125978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a55fda78a42'
down_revision: Union[str, None] = '0df1434883f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('target', sa.Enum('biometric_only', 'full_account', name='deletion_target'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', name='deletion_request_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_user_id'), 'deletion_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deletion_requests_user_id'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    # ### end Alembic commands ###
